/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FooCustomElementClient {
        "wham": string;
    }
}
declare global {
    interface HTMLFooCustomElementClientElement extends Components.FooCustomElementClient, HTMLStencilElement {
    }
    var HTMLFooCustomElementClientElement: {
        prototype: HTMLFooCustomElementClientElement;
        new (): HTMLFooCustomElementClientElement;
    };
    interface HTMLElementTagNameMap {
        "foo-custom-element-client": HTMLFooCustomElementClientElement;
    }
}
declare namespace LocalJSX {
    interface FooCustomElementClient {
        "wham"?: string;
    }
    interface IntrinsicElements {
        "foo-custom-element-client": FooCustomElementClient;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "foo-custom-element-client": LocalJSX.FooCustomElementClient & JSXBase.HTMLAttributes<HTMLFooCustomElementClientElement>;
        }
    }
}
