/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FooCustomElement {
        "wham": string;
    }
}
declare global {
    interface HTMLFooCustomElementElement extends Components.FooCustomElement, HTMLStencilElement {
    }
    var HTMLFooCustomElementElement: {
        prototype: HTMLFooCustomElementElement;
        new (): HTMLFooCustomElementElement;
    };
    interface HTMLElementTagNameMap {
        "foo-custom-element": HTMLFooCustomElementElement;
    }
}
declare namespace LocalJSX {
    interface FooCustomElement {
        "wham"?: string;
    }
    interface IntrinsicElements {
        "foo-custom-element": FooCustomElement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "foo-custom-element": LocalJSX.FooCustomElement & JSXBase.HTMLAttributes<HTMLFooCustomElementElement>;
        }
    }
}
