/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WixInternalHookComponent {
    }
}
declare global {
    interface HTMLWixInternalHookComponentElement extends Components.WixInternalHookComponent, HTMLStencilElement {
    }
    var HTMLWixInternalHookComponentElement: {
        prototype: HTMLWixInternalHookComponentElement;
        new (): HTMLWixInternalHookComponentElement;
    };
    interface HTMLElementTagNameMap {
        "wix-internal-hook-component": HTMLWixInternalHookComponentElement;
    }
}
declare namespace LocalJSX {
    interface WixInternalHookComponent {
    }
    interface IntrinsicElements {
        "wix-internal-hook-component": WixInternalHookComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wix-internal-hook-component": LocalJSX.WixInternalHookComponent & JSXBase.HTMLAttributes<HTMLWixInternalHookComponentElement>;
        }
    }
}
