/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WixDefaultCustomElement {
        "wham": string;
    }
}
declare global {
    interface HTMLWixDefaultCustomElementElement extends Components.WixDefaultCustomElement, HTMLStencilElement {
    }
    var HTMLWixDefaultCustomElementElement: {
        prototype: HTMLWixDefaultCustomElementElement;
        new (): HTMLWixDefaultCustomElementElement;
    };
    interface HTMLElementTagNameMap {
        "wix-default-custom-element": HTMLWixDefaultCustomElementElement;
    }
}
declare namespace LocalJSX {
    interface WixDefaultCustomElement {
        "wham"?: string;
    }
    interface IntrinsicElements {
        "wix-default-custom-element": WixDefaultCustomElement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wix-default-custom-element": LocalJSX.WixDefaultCustomElement & JSXBase.HTMLAttributes<HTMLWixDefaultCustomElementElement>;
        }
    }
}
